###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      container_name: currency-mysql
      working_dir: /application
      volumes:
        - data:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=currency
        - MYSQL_USER=currency
        - MYSQL_PASSWORD=root
      ports:
        - "9052:3306"

    webserver:
      image: nginx:alpine
      restart: always
      depends_on: 
        - php-fpm
      container_name: currency-webserver
      working_dir: /application
      volumes:
          - ./sources/backend:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9050:80"

    php-fpm:
      build: phpdocker/php-fpm
      depends_on: 
        - mysql
      container_name: currency-php-fpm
      working_dir: /application
      volumes:
        - ./sources/backend:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
      env_file:
        - ./phpdocker/php-fpm/.env
      links:
        - mysql 

    phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '9048:80'
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: root 
      links:
        - mysql 

volumes:
  data: